--ttest

create table dall2 as SELECT S_ID,exp FROM MICROARRAY_FACT JOIN PROBE ON MICROARRAY_FACT.PB_ID=PROBE.PB_ID 
  WHERE PROBE.PB_ID IN (SELECT PB_ID FROM PROBE INNER JOIN GENE_FACT ON PROBE.UID_PROBE=GENE_FACT.UID_GENEFACT WHERE GENE_FACT.UID_GENEFACT IN
  (select UID_GENEFACT FROM GENE_FACT WHERE GO_ID='12502')
);

--ALL
create table dall1 as SELECT S_ID FROM CLINICAL_FACT JOIN DISEASE ON CLINICAL_FACT.DS_ID=DISEASE.DS_ID WHERE DISEASE.DS_ID IN (SELECT DS_ID FROM DISEASE WHERE NAME='ALL');

--final exp in this
select count(exp) from dall2 where s_id in (select (dall2.s_id)from dall2 where  S_ID in (select s_id from dall1)); 


--not all
create table dnotall as SELECT S_ID FROM CLINICAL_FACT JOIN DISEASE ON CLINICAL_FACT.DS_ID=DISEASE.DS_ID 
  WHERE DISEASE.DS_ID IN (SELECT DS_ID FROM DISEASE WHERE not NAME='ALL');

--final exp in this
select count(exp) from dall2 where s_id in (select (dall2.s_id)from dall2 where  S_ID in (select s_id from DNOTALL)); 


--fstat change this table name

create table sid_exp_pbid_q51 as SELECT S_ID,exp FROM MICROARRAY_FACT JOIN PROBE ON MICROARRAY_FACT.PB_ID=PROBE.PB_ID 
WHERE PROBE.PB_ID IN (SELECT PB_ID FROM PROBE INNER JOIN GENE_FACT ON PROBE.UID_PROBE=GENE_FACT.UID_GENEFACT WHERE
GENE_FACT.UID_GENEFACT IN (select UID_GENEFACT FROM GENE_FACT WHERE GO_ID='12502')
);

--pearson correlation 
create table  q6_all as 
select count(s_id) from SID_EXP_PBID_Q5 where  S_ID in (SELECT S_ID FROM CLINICAL_FACT JOIN DISEASE ON CLINICAL_FACT.DS_ID=DISEASE.DS_ID 
    WHERE DISEASE.DS_ID IN (SELECT DS_ID FROM DISEASE WHERE NAME='ALL'));

